# Generated by Django 5.0.7 on 2024-09-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='status_operacional',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='unidade_medida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
